services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: managercep
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localsenha
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: manager-cep-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/managercep
      SPRING_DATASOURCE_USERNAME: localuser
      SPRING_DATASOURCE_PASSWORD: localsenha
      SPRING_JPA_HIBERNATE_DDL_AUTO: update